version: "3"
services:
  web:
    image: naimar/goodnews:v2
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 50M
    ports:
      - "80:80"
    volumes:
      - "/data/goodnews/html:/var/www/html"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
