FROM nginx

MAINTAINER someone <someone@somedomain>

COPY index.html /usr/share/nginx/html/

#RUN echo "this is sparta!!" > /usr/share/nginx/html/index.html

#EXPOSE 80

#ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]


