FROM nginx:latest

MAINTAINER someone <someone@somedomain>

RUN curl https://raw.githubusercontent.com/naimabdrahman/dock/master/Dockerfile/ngx/bear.html > /usr/share/nginx/html/index.html
#COPY ./index.html /usr/share/nginx/html/index.html
#COPY https://raw.githubusercontent.com/naimabdrahman/dock/master/Dockerfile/ngx/bear.html /usr/share/nginx/html/index.html
