 version: "3.6"
 services:
   gitlab:
     image: gitlab/gitlab-ce:latest
     ports:
       - "2222:22"
       - "80:80"
       - "443:443"
     volumes:
       - /srv/gitlab/data:/var/opt/gitlab
       - /srv/gitlab/logs:/var/log/gitlab
       - /srv/gitlab/config:/etc/gitlab
      
