version: "3"

services:

  registry:
    restart: always
    image: registry:latest
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/dock.crt
      REGISTRY_HTTP_TLS_KEY: /certs/dock.key
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      #- /path/data:/var/lib/registry
      - /etc/pki/tls/certs:/certs
      #- /path/auth:/auth


networks:
  web:
    driver: overlay
#    driver: bridge
