version: '3.1'

services:

  owncloud:
    image: owncloud
    deploy:
      replicas: 2
    restart: always
    ports:
      - 80:80
    volumes:
      - "/mnt/data/oc/html:/var/www/html"


  mysql:
#    image: mariadb
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
