version: "3"
services:
  web:
    image: naimar/goodnews:v2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    volumes:
      - "/data/goodnews/html:/var/www/html"
    networks:
      - webnet
    links:
      - db1:mysql
  db1:
    image: mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
    volumes:
      - /data/mysql/dir:/var/lib/mysql
    restart: always
    networks:
      - webnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

networks:
  webnet:
#    driver: bridge
