version: "3"
services:
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dock/gv1/data:/data
    ports:
      - 9000:9000
    networks:
      - web

networks:
  web:
    driver: overlay
