version: '3.1'

services:

  owncloud:
    image: owncloud
    restart: always
    ports:
      - 80:80

  mysql:
#    image: mariadb
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

