version: '3.1'

services:
  db:
    container_name: Mongo-db
    image: mongo:latest
    restart: always
    volumes:
      - ./myData:/data/db
    env_file:
      - ./secret-stuff.env
    ports:
      - 27020:27017
