version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/temp/kanboard_data:/var/www/app/data
      - /root/temp/kanboard_plugins:/var/www/app/plugins
      - /root/temp/kanboard_ssl:/etc/nginx/ssl
volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
  kanboard_ssl:
    driver: local

#u adm
#p adm
