FROM alpine
MAINTAINER someone <someone@somedomain>
RUN apk add apache2
RUN echo "This is alpine" > /var/www/localhost/htdocs/index.html
EXPOSE 80
CMD ["-D", "FOREGROUND"]
ENTRYPOINT ["/usr/sbin/httpd"]
