RUN yum -y install python ; sleep 1
RUN yum -y install wget ; sleep 1
RUN yum -y install python2-devel; sleep 1
RUN yum -y install gcc; sleep 1
RUN wget https://bootstrap.pypa.io/get-pip.py ; sleep 1
RUN python get-pip.py ; sleep 1
RUN echo -e "scipy\nnumpy\nmatplotlib\npandas\nsklearn" > requirements.txt ; sleep 1
RUN pip install subprocess32 ; sleep 1
RUN pip install -r requirements.txt ; sleep 1
