FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
#COPY *.csproj ./
COPY aspnetcoreapp/*.csproj ./
#COPY aspnetcoreapp/bin/release/net5.0/centos.7-x64/aspnetcoreapp.dll ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
#ENTRYPOINT ["dotnet", "aspnetapp.dll"]
ENTRYPOINT ["dotnet", "aspnetcoreapp.dll"]
