FROM centos
MAINTAINER someone <someone@somedomain>
RUN yum -y install wget git ; sleep 1
RUN wget https://bootstrap.pypa.io/get-pip.py ; sleep 2
RUN python get-pip.py ; sleep 2
RUN pip install flask-socketio ; sleep 2
RUN pip install flask-wtf ; sleep 2
RUN git clone https://github.com/naimabdrahman/Flask-SocketIO-Chatroom ; sleep 2
ENV FLASK_APP=/Flask-SocketIO-Chatroom/chat.py
EXPOSE 80
CMD ["run", "--host=0.0.0.0", "--port=80"]
ENTRYPOINT ["flask"]
