FROM centos
MAINTAINER someone <someone@somedomain>
RUN yum -y install python ; sleep 2
RUN yum -y install wget ; sleep 2
RUN yum -y install git ; sleep 2
RUN wget https://bootstrap.pypa.io/get-pip.py ; sleep 2
RUN python get-pip.py ; sleep 2
RUN pip install flask ; sleep 2
RUN git clone https://github.com/naimabdrahman/flask-blog ; sleep 2
ENV FLASK_APP=/flask-blog/flaskr.py
RUN flask initdb
EXPOSE 80
CMD ["run", "--host=0.0.0.0", "--port=80"]
ENTRYPOINT ["flask"]
