FROM nginx:latest

MAINTAINER someone <someone@somedomain>

#RUN curl https://raw.githubusercontent.com/naimabdrahman/dock/master/Dockerfile/ngx/nginx.conf.lb > /etc/nginx/nginx.conf
COPY ./nginx.conf.lb /etc/nginx/nginx.conf
#COPY https://raw.githubusercontent.com/naimabdrahman/dock/master/Dockerfile/ngx/bear.html /usr/share/nginx/html/index.html
